### ISSUE TITLE
Upgrade to MUI latest

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#111]
Simply make sure the peer dep in the new system is using the latest mui

**Comment by aaronsarnat** [comment]
@jonborchardt @arnavic do either of you happen to know which version of MUI we'd need to upgrade to in order to expose `useFlexGap` property in the Stack component?

I tried to use this property on Stacks in Dolma so it would use `gap` css instead of `margin` which was causing some minor responsive bugs. My guess as to why it didn't work is that the version we have in Dolma predates them adding this property.

You can see how the property works here (e.g. check out the codesandbox link):

https://mui.com/material-ui/react-stack/#flexbox-gap

**Comment by jonborchardt** [comment]
No. But by Jan 1 we will be on latest.

**Comment by aaronsarnat** [comment]
According to MUI's website latest is `5.14.19` as of this writing. Should we update the title to say "Upgrade MUI to latest" ?
