### ISSUE TITLE
default usage of varnish.Header is blue

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-mui#58]
I added a header to the skiff-template varnish2 branch, and it comes out blue....
i dont see how to make it white...
i think the default should be white.

![image](https://user-images.githubusercontent.com/8194065/225768299-d8001b49-9d53-45e8-bcfe-517a40f9da5c.png)

**Comment by arnavic** [comment]
this is a really interesting problem because upon looking at the browser inspector, seems like what's happening is the default AppBar styles are overriding the Header styles that have been implemented in our Header.tsx in varnish-mui... which is odd because if there was some sort of styling hierarchy override happening, it would ideally have surfaced itself in the varnish-mui docs. 
I am going to change the base AppBar styles to have it be white by default but I'm not sure at this point why this overriding is happening / what it will show up as in future component integrations with Skiff.

**Comment by jonborchardt** [comment]
we discussed in person and think that this is because styles needed more precedence

**Comment by arnavic** [comment]
will close this once we validate on skiff-template

**Comment by jonborchardt** [comment]
fixed
